### ISSUE TITLE
这个还要继续吗？

### ISSUE THREAD

**Issue by wszqkzqk** [linuxdeepin/deepin-compressor#1]
？？？

**Comment by BLumia** [comment]
v20 新项目之一，代码可能等正式版的社区版发布才会放出来。可以期待一下（

**Comment by wszqkzqk** [comment]
@BLumia 为什么不早点放出来...

**Comment by wszqkzqk** [comment]
代码在正式版后......

**Comment by BLumia** [comment]
> @BLumia 为什么不早点放出来...

内部已经在做代码和协议方面的核对了，就绪之后应该就会放出来了，不过这个事情本身也不是我在做所以我也不是很清楚计划安排和进度…

**Comment by wszqkzqk** [comment]
。。。
