### ISSUE TITLE
libcompressor-ChardetDetector.so is not be install

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/deepin-compressor#10]
libcompressor-ChardetDetector.so should be outputed and installed in %{_libdir}/deepin-compressor/plugins/. But it doesn't. So that the package can be installed.
![2021-04-20 21-28-35 的屏幕截图](https://user-images.githubusercontent.com/1880237/115404101-95739d00-a21f-11eb-96d9-b0e969393e72.png)

**Comment by hillwoodroc** [comment]
I see there is a link to the library:

https://github.com/linuxdeepin/deepin-compressor/blob/c10ecb80909eed830210dbeb899259f1fafb3338/3rdparty/interface/CMakeLists.txt#L63

Is it really in using?

**Comment by gaoxiang-ut** [comment]
> I see there is a link to the library:
> 
> https://github.com/linuxdeepin/deepin-compressor/blob/c10ecb80909eed830210dbeb899259f1fafb3338/3rdparty/interface/CMakeLists.txt#L63
> 
> Is it really in using?

That library is a static library. RPM compiles by default to generate a dynamic library. Now add the add_library parameter STATIC
