### ISSUE TITLE
请求压缩工具支持zstd格式的文件

### ISSUE THREAD

**Issue by wecli** [linuxdeepin/deepin-compressor#12]
环境：arch+dde桌面
archlinux软件包的压缩格式是zstd格式，目前deepin-compressor工具不能操作zstd格式的压缩文件。请求官方支持zstd格式的文件和deb格式的文件操作

**Comment by gaoxiang-ut** [comment]
你好，我们后续会和产品沟通规划

**Comment by gaoxiang-ut** [comment]
> 环境：arch+dde桌面
> archlinux软件包的压缩格式是zstd格式，目前deepin-compressor工具不能操作zstd格式的压缩文件。请求官方支持zstd格式的文件和deb格式的文件操作

你好，我们后续会和产品沟通规划
