### ISSUE TITLE
Deepin Compressor asks same password again when extracting two files with the same password

### ISSUE THREAD

**Issue by eduardomozart** [linuxdeepin/deepin-compressor#14]
Hello,
When I select two files through Deepin File Manager and select the option "Extract here", it asks the password for the first file and extract it, and when extracting the second file (that has the same password of the first one), it asks the password again to extract the second file, but the second file password is the same than the first file. These files are not related (e.g they are not ''.001'', ''.002'' extensions), they are independent from each other. But such behavior do not happen with 7-Zip and WinRAR. As a improvement, it would be cool that when Deepin Compressor is extracting two or more files and they are password protected, when extracting the second file, first it tries the same password from the second file and if they do not work so then it asks the password for the user, so he do not need to type the same password again. In my case was two files, but if there was more files, it would be troublesome.

**Comment by gaoxiang-ut** [comment]
> Hello,
> When I select two files through Deepin File Manager and select the option "Extract here", it asks the password for the first file and extract it, and when extracting the second file (that has the same password of the first one), it asks the password again to extract the second file, but the second file password is the same than the first file. These files are not related (e.g they are not ''.001'', ''.002'' extensions), they are independent from each other. But such behavior do not happen with 7-Zip and WinRAR. As a improvement, it would be cool that when Deepin Compressor is extracting two or more files and they are password protected, when extracting the second file, first it tries the same password from the second file and if they do not work so then it asks the password for the user, so he do not need to type the same password again. In my case was two files, but if there was more files, it would be troublesome.

Hello, what is your version? The latest version should not have this problem!

**Comment by Sky-Asher** [comment]
There has been no feedback on this problem for more than 1 month. The problem will be closed soon. Thank you for your support.
