### ISSUE TITLE
Crash when selecting a file

### ISSUE THREAD

**Issue by laradvance** [linuxdeepin/deepin-compressor#4]
Deepin archive manager freeze when selecting a file
![Screen Capture_20200822195023](https://user-images.githubusercontent.com/35951442/90955560-102dc200-e4b1-11ea-8616-9b84bd1ba38f.png)

**Comment by xmuli** [comment]
@felixonmars Has been informed to the nanjing team

**Comment by Sky-Asher** [comment]
This problem has been fixed, please update and try again
