### ISSUE TITLE
symbol lookup error: deepin-compressor: undefined symbol on deepin 1003

### ISSUE THREAD

**Issue by SuperEndermanSM** [linuxdeepin/deepin-compressor#9]
sy120zx@sy120zx-PC:~$ deepin-compressor 
deepin-compressor: symbol lookup error: deepin-compressor: undefined symbol: _ZN3Dtk6Widget7DDialog11eventFilterEP7QObjectP6QEvent
sy120zx@sy120zx-PC:~$ sudo apt update
请输入密码
[sudo] sy120zx 的密码：
验证成功
获取:2 https://mirrors.aliyun.com/docker-ce/linux/debian buster InRelease [44.4 kB]                           
命中:3 https://community-packages.deepin.com/deepin apricot InRelease                                         
命中:1 http://uos-packages.deepin.com/printer eagle InRelease                                                 
命中:4 http://sucdn.jerrywang.top  InRelease                                                                  
命中:5 https://cdn-package-store6.deepin.com/appstore eagle InRelease             
已下载 44.4 kB，耗时 16秒 (2,847 B/s)
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
所有软件包均为最新。
sy120zx@sy120zx-PC:~$ sudo apt reinstall deepin-compressor
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
下列软件包是自动安装的并且现在不需要了：
  deepin-elf-sign-tool deepin-elf-verify libddcutil0 libegl-mesa0:i386 libegl1:i386 libegl1-mesa:i386
  libgbm1:i386 libwayland-server0:i386 phantomjs python3-pyxattr rtmpdump youtube-dl
使用'sudo apt autoremove'来卸载它(它们)。
升级了 0 个软件包，新安装了 0 个软件包，重新安装了 1 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
需要下载 2,274 kB 的归档。
解压缩后会消耗 0 B 的额外空间。
获取:1 https://community-packages.deepin.com/deepin apricot/main amd64 deepin-compressor amd64 5.9.0.2-1 [2,274 kB]
已下载 2,274 kB，耗时 6秒 (365 kB/s)                                                                          
(正在读取数据库 ... 系统当前共安装有 290727 个文件和目录。)
准备解压 .../deepin-compressor_5.9.0.2-1_amd64.deb  ...
正在解压 deepin-compressor (5.9.0.2-1) 并覆盖 (5.9.0.2-1) ...
正在设置 deepin-compressor (5.9.0.2-1) ...
正在处理用于 bamfdaemon (0.5.4.1-1+eagle) 的触发器 ...
Rebuilding /usr/share/applications/bamf-2.index...
正在处理用于 desktop-file-utils (0.23-4) 的触发器 ...
正在处理用于 mime-support (3.62) 的触发器 ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 lastore-daemon (5.1.0.21-1) 的触发器 ...
正在处理用于 shared-mime-info (1.10.1-1+eagle) 的触发器 ...
sy120zx@sy120zx-PC:~$ deepin-compressor 
deepin-compressor: symbol lookup error: deepin-compressor: undefined symbol: _ZN3Dtk6Widget7DDialog11eventFilterEP7QObjectP6QEvent
sy120zx@sy120zx-PC:~$

**Comment by SuperEndermanSM** [comment]
`sy120zx@sy120zx-PC:~$ deepin-compressor 
deepin-compressor: symbol lookup error: deepin-compressor: undefined symbol: _ZN3Dtk6Widget7DDialog11eventFilterEP7QObjectP6QEvent
sy120zx@sy120zx-PC:~$ sudo apt update
请输入密码
[sudo] sy120zx 的密码：
验证成功
获取:2 https://mirrors.aliyun.com/docker-ce/linux/debian buster InRelease [44.4 kB]                           
命中:3 https://community-packages.deepin.com/deepin apricot InRelease                                         
命中:1 http://uos-packages.deepin.com/printer eagle InRelease                                                 
命中:4 http://sucdn.jerrywang.top  InRelease                                                                  
命中:5 https://cdn-package-store6.deepin.com/appstore eagle InRelease             
已下载 44.4 kB，耗时 16秒 (2,847 B/s)
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
所有软件包均为最新。
sy120zx@sy120zx-PC:~$ sudo apt reinstall deepin-compressor
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
下列软件包是自动安装的并且现在不需要了：
  deepin-elf-sign-tool deepin-elf-verify libddcutil0 libegl-mesa0:i386 libegl1:i386 libegl1-mesa:i386
  libgbm1:i386 libwayland-server0:i386 phantomjs python3-pyxattr rtmpdump youtube-dl
使用'sudo apt autoremove'来卸载它(它们)。
升级了 0 个软件包，新安装了 0 个软件包，重新安装了 1 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
需要下载 2,274 kB 的归档。
解压缩后会消耗 0 B 的额外空间。
获取:1 https://community-packages.deepin.com/deepin apricot/main amd64 deepin-compressor amd64 5.9.0.2-1 [2,274 kB]
已下载 2,274 kB，耗时 6秒 (365 kB/s)                                                                          
(正在读取数据库 ... 系统当前共安装有 290727 个文件和目录。)
准备解压 .../deepin-compressor_5.9.0.2-1_amd64.deb  ...
正在解压 deepin-compressor (5.9.0.2-1) 并覆盖 (5.9.0.2-1) ...
正在设置 deepin-compressor (5.9.0.2-1) ...
正在处理用于 bamfdaemon (0.5.4.1-1+eagle) 的触发器 ...
Rebuilding /usr/share/applications/bamf-2.index...
正在处理用于 desktop-file-utils (0.23-4) 的触发器 ...
正在处理用于 mime-support (3.62) 的触发器 ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 lastore-daemon (5.1.0.21-1) 的触发器 ...
正在处理用于 shared-mime-info (1.10.1-1+eagle) 的触发器 ...
sy120zx@sy120zx-PC:~$ deepin-compressor 
deepin-compressor: symbol lookup error: deepin-compressor: undefined symbol: _ZN3Dtk6Widget7DDialog11eventFilterEP7QObjectP6QEvent
sy120zx@sy120zx-PC:~$ 
`

**Comment by SuperEndermanSM** [comment]
有人在管么？

**Comment by z966768** [comment]
需要更新你的dtk环境

**Comment by z966768** [comment]
你好,确认这个问题更新dtk环境可以解决,暂时关闭次issues,有问题可以重启
